[package]
name = "create-bitcoin-transaction"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
hex-utilities = "0.1.3"
bitcoin = "0.29.1"
bitcoin-hd-keys = "=0.1.6"
sha2 = "=0.10.5"
